name: labart
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application. 
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  iconsax_flutter: ^1.0.0
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.5
  gif: ^2.3.0
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.15
  
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.2.1

  shared_preferences: ^2.2.2
  rive: ^0.13.20

  cached_network_image: ^3.4.1

  permission_handler: ^11.4.0

  image_picker: ^0.8.8+4
  provider: ^6.0.2
  
  shimmer: ^3.0.0

  share_plus: ^10.1.4
  fluttertoast: ^8.2.12

  flutter_file_downloader: ^1.1.0

  audioplayers: ^6.4.0
  vibration: ^3.1.3

  go_router: ^14.8.1

  multiple_search_selection: ^2.7.2
  http_parser: ^4.1.2
  mime: ^2.0.0

  skeletonizer: ^1.4.3

  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.2.1
  translator: ^1.0.3+1

  flutter_reaction_button: ^3.0.0+3

  equatable: ^2.0.5
  phosphor_flutter: ^2.1.0
  very_good_analysis: ^6.0.0
  universal_io: ^2.2.2

  flutter_gen_ai_chat_ui: ^2.1.2
  google_generative_ai: ^0.4.6
  flutter_streaming_text_markdown: ^1.1.0
  uuid: ^4.5.1
  # image_gallery_saver: ^2.0.3
  # # Permitir permisos y seleccionar imágenes de la galería o cámara y permitir descargar imágenes
  
  # image_picker: ^1.1.2

  # # Para compartir en otras plataformas
  # share_plus: ^10.1.4

  # # Para saber si hay conexión a internet
  # connectivity_plus: ^6.1.3

  # # Para notificaciones
  # firebase_messaging: ^15.2.4

flutter_native_splash:
  color: "#000000" # Color de fondo para el Splash Screen
# O la imagen que desees (en formato PNG, JPG, etc.)
  android: true # Habilitar para Android
  ios: false # Habilitar para iOS si lo deseas

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/logos/
    - lib/assets/animations/
    - lib/assets/backgrounds/
    - lib/assets/sounds/
    - assets/sounds/
    - lib/assets/animations/final_fantasy.riv

  #   - images/a_dot_ham.jpeg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
